name: CI

on: [ push, workflow_dispatch ]

jobs:
  unit-test:
    name: Run application unit tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x] 

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Load dependencies
      run: npm ci

    - name: Run unit tests
      run: npm test

    - name: Upload report to codacy
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_API_TOKEN }}
        coverage-reports: coverage/lcov.info
      continue-on-error: true

  lint:
    name: Lint application code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Load dependencies
      run: npm ci

    - name: Lint source code
      run: npm run lint

    - name: Lint markdown
      uses: reviewdog/action-remark-lint@v2.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review

    - name: shellcheck
      uses: reviewdog/action-shellcheck@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        pattern: "*.sh" 

    - name: Terraform lint
      uses: reviewdog/action-tflint@v1.1.1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
