name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]        
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Load dependencies
      run: npm ci

    - name: Run unit tests
      run: npm test

    - name: Upload report to codacy
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_API_TOKEN }}
        coverage-reports: coverage/lcov.info
      continue-on-error: true

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Load dependencies
      run: npm ci

    - name: Lint source code
      run: npm run lint

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Check Terraform code
      uses: triat/terraform-security-scan@v2.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tfsec_actions_comment: true
        tfsec_actions_working_dir: provision/
        tfsec_version: v0.37.0

    - name: Scan for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    needs:
      - unit-test
      - lint
      - security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the lambda
        run: echo "This will build the lambda"

    
      
