name: Run integration test against LATEST

on:
  schedule:
    - cron:  '15 10 * * *'
  workflow_dispatch:
    inputs:
      stations_bucket_name:
        description: 'Stations bucket name'
        required: true
        default: 'dschmitz-wasserstandinfo-stations-dev-99753'
      stations_object_key_name:
        description: 'Key name of stations object'
        required: true
        default: 'stations.json'
      lambda_function_name:
        description: 'Name of the lambda to integrate against'
        required: true
        default: 'wasserstandinfo-prefetch-dev:dev'

env:
  # todo fetch these names from terraform state
  STATIONS_BUCKET_NAME: ${{ github.event.inputs.stations_bucket_name || 'dschmitz-wasserstandinfo-stations-dev-99753' }}
  STATIONS_OBJECT_KEY_NAME: ${{ github.event.inputs.stations_object_key_name || 'stations.json' }}
  LAMBDA_FUNCTION_NAME: ${{ github.event.inputs.lambda_function_name || 'wasserstandinfo-prefetch-dev:dev' }}

jobs:
  run-integration-test:
    name: Run development master integration test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Load dependencies
      run: npm ci

    - name: Run integration-tests
      run:  ./node_modules/.bin/jest --verbose -c jest.config.integration-test.js
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # pragma: allowlist secret
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # pragma: allowlist secret 
        AWS_DEFAULT_REGION: eu-central-1

    - name: Slack Workflow Notification
      uses: Gamesight/slack-workflow-status@v1.0.1
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
        channel: '#github'
        name: ${{ github.workflow }}
        icon_emoji: ':poop:'
      
