name: Run integration test against LATEST

on:
  schedule:
    - cron:  '15 10 * * *'
  workflow_dispatch:
    inputs:
      stations_bucket_name:
        description: 'Stations bucket name'
        required: true
        default: 'dschmitz-wasserstandinfo-stations-dev-99753'
      stations_object_key_name:
        description: 'Key name of stations object'
        required: true
        default: 'stations.json'
      lambda_function_name:
        description: 'Name of the lambda to integrate against'
        required: true
        default: 'wasserstandinfo-prefetch-dev:$LATEST'

env:
  STATIONS_BUCKET_NAME: ${{ github.event.inputs.stations_bucket_name || 'dschmitz-wasserstandinfo-stations-dev-99753' }}
  STATIONS_OBJECT_KEY_NAME: ${{ github.event.inputs.stations_object_key_name || 'stations.json' }}
  LAMBDA_FUNCTION_NAME: ${{ github.event.inputs.lambda_function_name || 'wasserstandinfo-prefetch-dev' }}

jobs:
  run-integration-test:
    name: Run development master integration test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Load dependencies
      run: npm ci

    - name: Run integration-tests
      run:  ./node_modules/.bin/jest --verbose -c jest.config.integration-test.js
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # pragma: allowlist secret
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # pragma: allowlist secret
        AWS_DEFAULT_REGION: eu-central-1

    - name: Slack Workflow Notification
      uses: rtCamp/action-slack-notify@v2@v2.2.0
      env:
        SLACK_CHANNEL: '#github'
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: ${{ github.workflow }}
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

