name: Terraform Lint and Security Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform lint
      uses: reviewdog/action-tflint@v1.1.1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Scan Terraform for vulnerabilities
      uses: reviewdog/action-tfsec@v1.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        fail_on_error: true
