name: Dev deployment

on:
  push: 
    branches: [ master ]
  workflow_dispatch:

jobs:
  plan-and-apply:
    name: Plan and apply function infrastructure
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # pragma: allowlist secret
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # pragma: allowlist secret 
      AWS_DEFAULT_REGION: eu-central-1
      TF_INPUT: false
      TF_IN_AUTOMATION: true
      APP_VERSION: ${GITHUB_REF}
      TF_VAR_app_version: ${GITHUB_REF}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.4
        terraform_wrapper: false

    - name: Init
      run: terraform init
      working-directory: provision/function
    
    - name: Upload source bundle
      run: |
        apt-get update
        apt install -y jq
        ./scripts/bundle.sh

    - name: Plan
      working-directory: provision/function
      run: |
        echo "Deploying ${APP_VERSION} version"
        terraform plan -input=false -no-color -out function.tfplan
      
    - name: Apply
      working-directory: provision/function
      if: github.ref == 'refs/heads/master'
      run: terraform apply function.tfplan
